### ISSUE TITLE
PowerPanel® Personal v2.3.0

### ISSUE THREAD

**Issue by olimpiumarius** [raleighlittles/CyberPowerUPS-Influx#1]
Hello all,

PowerPanel® Personal v2.3.0 for Windows not work in windows11,does not display any information in the menu and the message power panel personal service is not ready appears!
if I go to the device to usb in windows 11 it sees CP1500EPFCLCD

**Comment by raleighlittles** [comment]
Thanks for your issue.

Unfortunately, I don't have access to a Windows computer to test this with. If you can figure out the issue and would like to add Windows compatibility to this tool, I would be happy to accept PRs.
